TaskManager/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, login_user, logout_user
from .db_models import User
from . import db
from sqlalchemy.exc import SQLAlchemyError, NoResultFound
from .models.responses import SimpleResponse

auth = Blueprint("auth", __name__)


def perform_login(username, password) -> SimpleResponse:
    try:
        user = User.query.filter_by(username=username).one()
    except NoResultFound as e:
        return SimpleResponse(False, f"Username {username} not found", e)
    except SQLAlchemyError as e:
        return SimpleResponse(False, f"Database error: {e}", e)
    password_correct = user.check_password(password)
    if password_correct is not True:
        return SimpleResponse(False, "Wrong password!")

    login_user(user, remember=True)
    return SimpleResponse(True)

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    username = request.form["username"]
    password = request.form["password"]

    result = perform_login(username, password)
    if result.success is True:
        flash(f"You have been logged in correctly, welcome {username}", category="success")
        return redirect(url_for("views.index"))
    else:
        flash(f"You have not been logged in: {result.message}", category="error")
        return render_template("login.html")



def is_email_available(email) -> bool:
    existence_query = User.query.filter_by(email=email).exists()
    return not db.session.query(existence_query).scalar()

def is_username_available(username) -> bool:
    existence_query = User.query.filter_by(username=username).exists()
    return not db.session.query(existence_query).scalar()

def validate_signup(email, username, password1, password2) -> bool:
    success = True
    if password1 != password2:
        flash("Passwords don't match!", category="error")
        success = False
    if len(username) <= 3:
        flash("Username too short! Should be at least 4 characters", category="error")
        success = False
    if len(password1) <=7: #passwords are equal at this point
        flash("Password too short! Should be at least 8 characters", category="error")
        success = False
    # check if either email or username already used
    if is_username_available(username) is False:
        flash(f"Username {username} is already taken!", category="error")
        success = False
    if is_email_available(email) is False:
        flash(f"Account registered on {email} already exists!", category="error")
        success = False
    return success

def register_user(email, username, password) -> SimpleResponse:
    """Function to register a new user in the database."""
    new_user = User(email, username, password)
    try:
        db.session.add(new_user)
        db.session.commit()
    except SQLAlchemyError as e:
        db.session.rollback()
        return SimpleResponse(False, str(e), e)
    return SimpleResponse(True)

@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    email = request.form["email"]
    username = request.form["username"]
    password1 = request.form["password1"]
    password2 = request.form["password2"]
    if validate_signup(email, username, password1, password2) is False:
        return render_template("register.html")

    result = register_user(email, username, password1)
    if result.success is True:
        flash("Account registered successfully!", category="success")
    if result.success is not True:
        flash(f"Account was not registered: {result.message}", category="error")
    return render_template("register.html")

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return render_template("after_logout.html")

TaskManager/website/templates/after_logout.html
{% extends "base.html"%}
{% block title %}
    Bye
{% endblock %}
{% block content %}
	You have been logged out.
    <div>
        <a href="{{ url_for('auth.login') }}">Login again?</a>
        <a href="/"> Home</a>
    </div>
{% endblock %}

TaskManager/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Home page {% endblock %}</title>
    {% block stylesheets %} {% endblock %}
</head>
<body>
    <nav>
        <div>
            <a id="login" href="/login">log in</a>
            <a id="register" href="/register">register</a>
            {% if current_user.is_authenticated %}
                <a id="logout" href="/logout">log out</a>
                <a id="home" href="/">home</a>
                <a id="terminal" href="/terminal">terminal</a>
            {% endif %}
        </div>
    </nav>
    <br>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == "success" %}
                    <div style="color: green;">{{ message }}</div>
                {% else %}
                    <div style="color: red;">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}Hi :){% endblock %}
</body>
</html>

TaskManager/website/templates/home.html
{% extends "base.html" %}
{% block title %}
    Home
{% endblock %}
{% block content %}
	{% if current_user.is_authenticated %}
        <h1>Welcome, {{ current_user.username }}</h1>
    {% else %}
        <h1>Log in to see content of this page</h1>
    {% endif %}
{% endblock %}

TaskManager/website/templates/login.html
{% extends "base.html"%}
{% block title %}
    Sign In
{% endblock %}

{% block content %}
    <style>
        .center-wrapper {
            display: flex;
            justify-content: center;
            min-height: 100vh; /* or any height you want */
        }
    </style>
    <div class="center-wrapper">
        <form method="post" style="margin: 0 auto; width: auto">
            <h3>Sign in </h3>
            <div>
                <label for="username">username </label>
                <input type="text" id="username" name="username" placeholder="Enter username" required>
            </div>
            <div>
                <label for="password">password</label>
                <input type="password" id="password" name="password" placeholder="Enter password" required>
            </div>
            <br>
            <button type="submit">Sign in!</button>
        </form>
    </div>

{% endblock %}

TaskManager/website/templates/register.html
{% extends "base.html"%}
{% block title %}
    Sign Up
{% endblock %}
{% block content %}
    <style>
        .center-wrapper {
            display: flex;
            justify-content: center;
            min-height: 100vh; /* or any height you want */
        }
    </style>
    <div class="center-wrapper">
        <form method="post">
            <h3 style="text-align: center">Sign up </h3>
            <div>
                <label for="email">email </label>
                <input type="email" id="email" name="email" placeholder="Enter email" required>
            </div>
            <div>
                <label for="username">username </label>
                <input type="text" id="username" name="username" placeholder="Enter desired username" required>
            </div>
            <div>
                <label for="password1">password </label>
                <input type="password" id="password1" name="password1" placeholder="Enter password" required>
            </div>
            <div>
                <label for="password2">email address </label>
                <input type="password" id="password2" name="password2" placeholder="Repeat password" required>
            </div>
            <br>
            <button type="submit">Sign up!</button>
        </form>
    </div>


{% endblock %}

TaskManager/website/templates/terminal.html
{% extends "base.html" %}
{% block title %}
    Terminal
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/terminal.css') }}">
{% endblock %}
{% block content %}
	<h1>Welcome to the terminal {{ current_user.username }}!</h1>
    <p>Here you can view, edit and delete your tasks</p>
    <br>
    <div class="terminal-container">
      <div class="output" id="terminal-output">
        <!-- Commands and responses will appear here -->
      </div>
      <div class="input-line">
        <span class="prompt">$</span>
        <input type="text" class="command-input" id="command-input" autofocus>
      </div>
    </div>

    <script type="module" src="../static/js/terminal.js" defer></script>
{% endblock %}